import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import React from 'react';
import {FaCheckCircle} from 'react-icons/fa';
import {FaCheck, FaTimes} from 'react-icons/fa';
import {FaShieldAlt, FaTachometerAlt, FaSyncAlt, FaDatabase, FaBug, FaChartLine} from 'react-icons/fa';
import {FaShoppingCart, FaClock, FaUserShield, FaHistory, FaBusinessTime, FaHeadset} from 'react-icons/fa';
import {FaChevronDown} from 'react-icons/fa';
import {FaPhoneAlt} from 'react-icons/fa';

export default function SupportAndMaintenancePage() {
	return (
		<>
			<Head>
				<title>Support and Maintenance</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			{/* Hero Section */}
			<section class="hero-gradient text-white">
				<div class="container mx-auto px-4 py-20 md:py-28">
					<div class="max-w-4xl mx-auto text-center">
						<h1 class="text-4xl md:text-5xl font-bold leading-tight mb-6">eCommerce Support & Maintenance Services</h1>
						<p class="text-xl text-blue-100 mb-8">
							Proactive care for your online store. Keep your eCommerce business running smoothly while we handle the
							technical details.
						</p>
						<div class="flex flex-col sm:flex-row justify-center space-y-4 sm:space-y-0 sm:space-x-4">
							<a
								href="#support-plans"
								class="bg-white text-blue-600 px-6 py-3 rounded-md font-medium hover:bg-gray-100 transition text-center"
							>
								View Plans
							</a>
							<a
								href="#maintenance-services"
								class="border-2 border-white text-white px-6 py-3 rounded-md font-medium hover:bg-white hover:text-blue-600 transition text-center"
							>
								Our Services
							</a>
						</div>
					</div>
				</div>
			</section>

			{/* Support Section */}
			<section className="py-20 bg-white">
				<div className="container mx-auto px-4">
					<div className="max-w-4xl mx-auto">
						<div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
							<div>
								<h2 className="text-3xl md:text-4xl font-bold mb-6">Your Store Always Open, Always Secure</h2>
								<p className="text-xl text-gray-600 mb-6">
									eCommerce never sleeps, and neither does our support. We provide the technical backbone so you can
									focus on growing your business, not fixing problems.
								</p>
								<div className="space-y-4">
									<div className="flex items-start">
										<div className="flex-shrink-0 mt-1 text-blue-600 mr-4">
											<FaCheckCircle />
										</div>
										<div>
											<h3 className="text-lg font-bold">Proactive Monitoring</h3>
											<p className="text-gray-600">We catch and fix issues before they impact your customers.</p>
										</div>
									</div>
									<div className="flex items-start">
										<div className="flex-shrink-0 mt-1 text-blue-600 mr-4">
											<FaCheckCircle />
										</div>
										<div>
											<h3 className="text-lg font-bold">Rapid Response</h3>
											<p className="text-gray-600">Dedicated support team with fast resolution times.</p>
										</div>
									</div>
									<div className="flex items-start">
										<div className="flex-shrink-0 mt-1 text-blue-600 mr-4">
											<FaCheckCircle />
										</div>
										<div>
											<h3 className="text-lg font-bold">Security First</h3>
											<p className="text-gray-600">Regular updates and patches to protect your business.</p>
										</div>
									</div>
								</div>
							</div>
							<div className="bg-gray-50 p-6 rounded-xl shadow-lg">
								<img
									src="https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80"
									alt="eCommerce Support"
									className="rounded-lg w-full h-auto"
								/>
							</div>
						</div>
					</div>
				</div>
			</section>

			{/* Support Plans */}
			<section id="support-plans" className="py-20 bg-gray-50">
				<div className="container mx-auto px-4">
					<div className="text-center mb-16">
						<h2 className="text-3xl md:text-4xl font-bold mb-4">Comprehensive Support Plans</h2>
						<p className="text-xl text-gray-600 max-w-3xl mx-auto">
							Choose the level of support that matches your business needs.
						</p>
					</div>

					<div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-6xl mx-auto">
						{/* Basic Plan */}
						<div className="plan-card bg-white p-8 rounded-xl shadow-md transition duration-300 hover:shadow-xl hover:scale-105">
							<h3 className="text-2xl font-bold mb-4 text-center">Basic</h3>
							<div className="text-4xl font-bold mb-6 text-center">
								$299<span className="text-lg text-gray-500">/month</span>
							</div>
							<ul className="space-y-4 mb-8">
								<li className="flex items-start">
									<div className="flex-shrink-0 mt-1 text-blue-600 mr-3">
										<FaCheck />
									</div>
									<span>24/7 Monitoring</span>
								</li>
								<li className="flex items-start">
									<div className="flex-shrink-0 mt-1 text-blue-600 mr-3">
										<FaCheck />
									</div>
									<span>Security Updates</span>
								</li>
								<li className="flex items-start">
									<div className="flex-shrink-0 mt-1 text-blue-600 mr-3">
										<FaCheck />
									</div>
									<span>Bug Fixes (2 hours/month)</span>
								</li>
								<li className="flex items-start">
									<div className="flex-shrink-0 mt-1 text-gray-400 mr-3">
										<FaTimes />
									</div>
									<span className="text-gray-500">Priority Support</span>
								</li>
								<li className="flex items-start">
									<div className="flex-shrink-0 mt-1 text-gray-400 mr-3">
										<FaTimes />
									</div>
									<span className="text-gray-500">Monthly Performance Reports</span>
								</li>
							</ul>
							<a
								href="contact.html"
								className="block text-center bg-gray-200 text-gray-800 px-6 py-3 rounded-md font-medium hover:bg-gray-300 transition"
							>
								Get Basic Plan
							</a>
						</div>

						{/* Pro Plan */}
						<div className="plan-card bg-white p-8 rounded-xl shadow-md border-2 border-blue-600 transition duration-300 hover:shadow-xl hover:scale-105 transform scale-105">
							<div className="bg-blue-600 text-white text-sm font-bold px-4 py-1 rounded-full inline-block mb-4">
								MOST POPULAR
							</div>
							<h3 className="text-2xl font-bold mb-4 text-center">Pro</h3>
							<div className="text-4xl font-bold mb-6 text-center">
								$599<span className="text-lg text-gray-500">/month</span>
							</div>
							<ul className="space-y-4 mb-8">
								<li className="flex items-start">
									<div className="flex-shrink-0 mt-1 text-blue-600 mr-3">
										<FaCheck />
									</div>
									<span>24/7 Monitoring & Alerts</span>
								</li>
								<li className="flex items-start">
									<div className="flex-shrink-0 mt-1 text-blue-600 mr-3">
										<FaCheck />
									</div>
									<span>Security Updates & Patches</span>
								</li>
								<li className="flex items-start">
									<div className="flex-shrink-0 mt-1 text-blue-600 mr-3">
										<FaCheck />
									</div>
									<span>Bug Fixes (5 hours/month)</span>
								</li>
								<li className="flex items-start">
									<div className="flex-shrink-0 mt-1 text-blue-600 mr-3">
										<FaCheck />
									</div>
									<span>Priority Support (4hr response)</span>
								</li>
								<li className="flex items-start">
									<div className="flex-shrink-0 mt-1 text-blue-600 mr-3">
										<FaCheck />
									</div>
									<span>Monthly Performance Reports</span>
								</li>
							</ul>
							<a
								href="contact.html"
								className="block text-center bg-blue-600 text-white px-6 py-3 rounded-md font-medium hover:bg-blue-700 transition"
							>
								Get Pro Plan
							</a>
						</div>

						{/* Enterprise Plan */}
						<div className="plan-card bg-white p-8 rounded-xl shadow-md transition duration-300 hover:shadow-xl hover:scale-105">
							<h3 className="text-2xl font-bold mb-4 text-center">Enterprise</h3>
							<div className="text-4xl font-bold mb-6 text-center">
								$1,299<span className="text-lg text-gray-500">/month</span>
							</div>
							<ul className="space-y-4 mb-8">
								<li className="flex items-start">
									<div className="flex-shrink-0 mt-1 text-blue-600 mr-3">
										<FaCheck />
									</div>
									<span>24/7 Monitoring & Immediate Response</span>
								</li>
								<li className="flex items-start">
									<div className="flex-shrink-0 mt-1 text-blue-600 mr-3">
										<FaCheck />
									</div>
									<span>Advanced Security Management</span>
								</li>
								<li className="flex items-start">
									<div className="flex-shrink-0 mt-1 text-blue-600 mr-3">
										<FaCheck />
									</div>
									<span>Unlimited Bug Fixes</span>
								</li>
								<li className="flex items-start">
									<div className="flex-shrink-0 mt-1 text-blue-600 mr-3">
										<FaCheck />
									</div>
									<span>VIP Support (1hr response)</span>
								</li>
								<li className="flex items-start">
									<div className="flex-shrink-0 mt-1 text-blue-600 mr-3">
										<FaCheck />
									</div>
									<span>Weekly Performance Reports</span>
								</li>
							</ul>
							<a
								href="contact.html"
								className="block text-center bg-gray-800 text-white px-6 py-3 rounded-md font-medium hover:bg-gray-900 transition"
							>
								Get Enterprise Plan
							</a>
						</div>
					</div>
				</div>
			</section>

			{/* Maintenance Services */}
			<section id="maintenance-services" className="py-20 bg-white">
				<div className="container mx-auto px-4">
					<div className="text-center mb-16">
						<h2 className="text-3xl md:text-4xl font-bold mb-4">Our Maintenance Services</h2>
						<p className="text-xl text-gray-600 max-w-3xl mx-auto">
							Comprehensive care to keep your store performing at its best.
						</p>
					</div>

					<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 max-w-6xl mx-auto">
						{/* Service 1 */}
						<div className="service-card bg-gray-50 p-8 rounded-xl shadow-md transition duration-300">
							<div className="w-16 h-16 bg-blue-100 rounded-lg flex items-center justify-center mb-6">
								<FaShieldAlt className="text-blue-600 text-2xl" />
							</div>
							<h3 className="text-xl font-bold mb-3">Security Maintenance</h3>
							<p className="text-gray-600 mb-4">
								Regular security patches, malware scans, and vulnerability assessments to protect your store and
								customer data.
							</p>
							<div className="flex flex-wrap gap-2">
								<span className="bg-blue-100 text-blue-800 text-xs px-2 py-1 rounded">PCI Compliance</span>
								<span className="bg-blue-100 text-blue-800 text-xs px-2 py-1 rounded">Firewall Updates</span>
								<span className="bg-blue-100 text-blue-800 text-xs px-2 py-1 rounded">Security Patches</span>
							</div>
						</div>

						{/* Service 2 */}
						<div className="service-card bg-gray-50 p-8 rounded-xl shadow-md transition duration-300">
							<div className="w-16 h-16 bg-green-100 rounded-lg flex items-center justify-center mb-6">
								<FaTachometerAlt className="text-green-600 text-2xl" />
							</div>
							<h3 className="text-xl font-bold mb-3">Performance Optimization</h3>
							<p className="text-gray-600 mb-4">
								Ongoing speed improvements, database optimizations, and resource management to ensure fast page loads.
							</p>
							<div className="flex flex-wrap gap-2">
								<span className="bg-green-100 text-green-800 text-xs px-2 py-1 rounded">Speed Tests</span>
								<span className="bg-green-100 text-green-800 text-xs px-2 py-1 rounded">Caching</span>
								<span className="bg-green-100 text-green-800 text-xs px-2 py-1 rounded">Image Optimization</span>
							</div>
						</div>

						{/* Service 3 */}
						<div className="service-card bg-gray-50 p-8 rounded-xl shadow-md transition duration-300">
							<div className="w-16 h-16 bg-purple-100 rounded-lg flex items-center justify-center mb-6">
								<FaSyncAlt className="text-purple-600 text-2xl" />
							</div>
							<h3 className="text-xl font-bold mb-3">Platform Updates</h3>
							<p className="text-gray-600 mb-4">
								Careful management of platform, theme, and plugin updates to maintain compatibility and security.
							</p>
							<div className="flex flex-wrap gap-2">
								<span className="bg-purple-100 text-purple-800 text-xs px-2 py-1 rounded">Version Control</span>
								<span className="bg-purple-100 text-purple-800 text-xs px-2 py-1 rounded">Change Logs</span>
								<span className="bg-purple-100 text-purple-800 text-xs px-2 py-1 rounded">Rollback Plans</span>
							</div>
						</div>

						{/* Service 4 */}
						<div className="service-card bg-gray-50 p-8 rounded-xl shadow-md transition duration-300">
							<div className="w-16 h-16 bg-red-100 rounded-lg flex items-center justify-center mb-6">
								<FaDatabase className="text-red-600 text-2xl" />
							</div>
							<h3 className="text-xl font-bold mb-3">Backup Management</h3>
							<p className="text-gray-600 mb-4">
								Automated daily backups with offsite storage and easy restoration options for disaster recovery.
							</p>
							<div className="flex flex-wrap gap-2">
								<span className="bg-red-100 text-red-800 text-xs px-2 py-1 rounded">Daily Backups</span>
								<span className="bg-red-100 text-red-800 text-xs px-2 py-1 rounded">Cloud Storage</span>
								<span className="bg-red-100 text-red-800 text-xs px-2 py-1 rounded">One-Click Restore</span>
							</div>
						</div>

						{/* Service 5 */}
						<div className="service-card bg-gray-50 p-8 rounded-xl shadow-md transition duration-300">
							<div className="w-16 h-16 bg-yellow-100 rounded-lg flex items-center justify-center mb-6">
								<FaBug className="text-yellow-600 text-2xl" />
							</div>
							<h3 className="text-xl font-bold mb-3">Bug Fixes</h3>
							<p className="text-gray-600 mb-4">
								Quick resolution of technical issues, broken functionality, and unexpected errors.
							</p>
							<div className="flex flex-wrap gap-2">
								<span className="bg-yellow-100 text-yellow-800 text-xs px-2 py-1 rounded">Error Tracking</span>
								<span className="bg-yellow-100 text-yellow-800 text-xs px-2 py-1 rounded">Priority Fixes</span>
								<span className="bg-yellow-100 text-yellow-800 text-xs px-2 py-1 rounded">Code Reviews</span>
							</div>
						</div>

						{/* Service 6 */}
						<div className="service-card bg-gray-50 p-8 rounded-xl shadow-md transition duration-300">
							<div className="w-16 h-16 bg-indigo-100 rounded-lg flex items-center justify-center mb-6">
								<FaChartLine className="text-indigo-600 text-2xl" />
							</div>
							<h3 className="text-xl font-bold mb-3">Performance Reporting</h3>
							<p className="text-gray-600 mb-4">
								Regular insights into your store's technical health, speed metrics, and security status.
							</p>
							<div className="flex flex-wrap gap-2">
								<span className="bg-indigo-100 text-indigo-800 text-xs px-2 py-1 rounded">Monthly Reports</span>
								<span className="bg-indigo-100 text-indigo-800 text-xs px-2 py-1 rounded">Core Web Vitals</span>
								<span className="bg-indigo-100 text-indigo-800 text-xs px-2 py-1 rounded">Uptime Monitoring</span>
							</div>
						</div>
					</div>
				</div>
			</section>

			{/* Support Process */}
			<section class="py-20 bg-gray-50">
				<div class="container mx-auto px-4">
					<div class="text-center mb-16">
						<h2 class="text-3xl md:text-4xl font-bold mb-4">Our Support Process</h2>
						<p class="text-xl text-gray-600 max-w-3xl mx-auto">
							Clear, efficient workflows to resolve your issues quickly.
						</p>
					</div>

					<div class="grid grid-cols-1 md:grid-cols-5 gap-8 max-w-6xl mx-auto">
						<div class="process-step bg-white p-8 rounded-xl shadow-md text-center relative">
							<div class="w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center mb-6 mx-auto">
								<span class="text-blue-600 font-bold text-xl">1</span>
							</div>
							<h3 class="text-xl font-bold mb-3">Issue Identification</h3>
							<p class="text-gray-600">Automated monitoring detects problems or you submit a support ticket.</p>
						</div>

						<div class="process-step bg-white p-8 rounded-xl shadow-md text-center relative">
							<div class="w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center mb-6 mx-auto">
								<span class="text-blue-600 font-bold text-xl">2</span>
							</div>
							<h3 class="text-xl font-bold mb-3">Priority Assessment</h3>
							<p class="text-gray-600">We categorize and prioritize based on business impact.</p>
						</div>

						<div class="process-step bg-white p-8 rounded-xl shadow-md text-center relative">
							<div class="w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center mb-6 mx-auto">
								<span class="text-blue-600 font-bold text-xl">3</span>
							</div>
							<h3 class="text-xl font-bold mb-3">Technical Analysis</h3>
							<p class="text-gray-600">Our experts diagnose the root cause of the issue.</p>
						</div>

						<div class="process-step bg-white p-8 rounded-xl shadow-md text-center relative">
							<div class="w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center mb-6 mx-auto">
								<span class="text-blue-600 font-bold text-xl">4</span>
							</div>
							<h3 class="text-xl font-bold mb-3">Solution Implementation</h3>
							<p class="text-gray-600">We implement fixes following change management protocols.</p>
						</div>

						<div class="process-step bg-white p-8 rounded-xl shadow-md text-center">
							<div class="w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center mb-6 mx-auto">
								<span class="text-blue-600 font-bold text-xl">5</span>
							</div>
							<h3 class="text-xl font-bold mb-3">Verification & Documentation</h3>
							<p class="text-gray-600">We confirm resolution and update knowledge base.</p>
						</div>
					</div>
				</div>
			</section>

			{/* Guaranteed Response Times */}
			<section class="py-20 bg-white">
				<div class="container mx-auto px-4">
					<div class="text-center mb-16">
						<h2 class="text-3xl md:text-4xl font-bold mb-4">Guaranteed Response Times</h2>
						<p class="text-xl text-gray-600 max-w-3xl mx-auto">
							We understand urgency when your store is experiencing issues.
						</p>
					</div>

					<div class="max-w-4xl mx-auto overflow-hidden shadow-md rounded-lg">
						<table class="min-w-full divide-y divide-gray-200">
							<thead class="bg-gray-50">
								<tr>
									<th
										scope="col"
										class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
									>
										Priority Level
									</th>
									<th
										scope="col"
										class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
									>
										Description
									</th>
									<th
										scope="col"
										class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
									>
										Initial Response
									</th>
									<th
										scope="col"
										class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
									>
										Resolution Target
									</th>
								</tr>
							</thead>
							<tbody class="bg-white divide-y divide-gray-200">
								<tr>
									<td class="px-6 py-4 whitespace-nowrap">
										<span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800">
											Critical
										</span>
									</td>
									<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
										Store down or major functionality broken
									</td>
									<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">30 minutes</td>
									<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">4 hours</td>
								</tr>
								<tr>
									<td class="px-6 py-4 whitespace-nowrap">
										<span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-yellow-100 text-yellow-800">
											High
										</span>
									</td>
									<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
										Significant impact on business operations
									</td>
									<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">2 hours</td>
									<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">24 hours</td>
								</tr>
								<tr>
									<td class="px-6 py-4 whitespace-nowrap">
										<span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-blue-100 text-blue-800">
											Medium
										</span>
									</td>
									<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">Minor functionality issues</td>
									<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">8 hours</td>
									<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">3 business days</td>
								</tr>
								<tr>
									<td class="px-6 py-4 whitespace-nowrap">
										<span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
											Low
										</span>
									</td>
									<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">Cosmetic or non-urgent requests</td>
									<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">24 hours</td>
									<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">1 week</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</section>

			{/* Why Choose eComReflex Support */}
			<section className="py-20 bg-gray-50">
				<div className="container mx-auto px-4">
					<div className="max-w-4xl mx-auto text-center mb-16">
						<h2 className="text-3xl md:text-4xl font-bold mb-4">Why Choose eComReflex Support?</h2>
						<p className="text-xl text-gray-600">We're not just another support team - we're eCommerce specialists.</p>
					</div>

					<div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-6xl mx-auto">
						{/* Reason 1 */}
						<div className="bg-white p-8 rounded-xl shadow-md">
							<div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center mb-6">
								<FaShoppingCart className="text-blue-600 text-xl" />
							</div>
							<h3 className="text-xl font-bold mb-3">eCommerce Focus</h3>
							<p className="text-gray-600">
								We specialize exclusively in eCommerce platforms, not generic web support.
							</p>
						</div>

						{/* Reason 2 */}
						<div className="bg-white p-8 rounded-xl shadow-md">
							<div className="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center mb-6">
								<FaClock className="text-green-600 text-xl" />
							</div>
							<h3 className="text-xl font-bold mb-3">Proactive Monitoring</h3>
							<p className="text-gray-600">We catch and resolve 62% of issues before they affect your store.</p>
						</div>

						{/* Reason 3 */}
						<div className="bg-white p-8 rounded-xl shadow-md">
							<div className="w-12 h-12 bg-purple-100 rounded-lg flex items-center justify-center mb-6">
								<FaUserShield className="text-purple-600 text-xl" />
							</div>
							<h3 className="text-xl font-bold mb-3">Security Experts</h3>
							<p className="text-gray-600">Certified professionals keeping your store PCI compliant and secure.</p>
						</div>

						{/* Reason 4 */}
						<div className="bg-white p-8 rounded-xl shadow-md">
							<div className="w-12 h-12 bg-red-100 rounded-lg flex items-center justify-center mb-6">
								<FaHistory className="text-red-600 text-xl" />
							</div>
							<h3 className="text-xl font-bold mb-3">Change Tracking</h3>
							<p className="text-gray-600">
								Detailed logs of all changes made to your store for complete transparency.
							</p>
						</div>

						{/* Reason 5 */}
						<div className="bg-white p-8 rounded-xl shadow-md">
							<div className="w-12 h-12 bg-yellow-100 rounded-lg flex items-center justify-center mb-6">
								<FaBusinessTime className="text-yellow-600 text-xl" />
							</div>
							<h3 className="text-xl font-bold mb-3">Peak Period Support</h3>
							<p className="text-gray-600">Extra resources during holidays and sales events when you need it most.</p>
						</div>

						{/* Reason 6 */}
						<div className="bg-white p-8 rounded-xl shadow-md">
							<div className="w-12 h-12 bg-indigo-100 rounded-lg flex items-center justify-center mb-6">
								<FaHeadset className="text-indigo-600 text-xl" />
							</div>
							<h3 className="text-xl font-bold mb-3">Dedicated Account Manager</h3>
							<p className="text-gray-600">
								Single point of contact who understands your business (Pro & Enterprise plans).
							</p>
						</div>
					</div>
				</div>
			</section>

			{/* Support Success Stories */}
			<section className="py-20 bg-white">
				<div className="container mx-auto px-4">
					<div className="text-center mb-16">
						<h2 className="text-3xl md:text-4xl font-bold mb-4">Support Success Stories</h2>
						<p className="text-xl text-gray-600 max-w-3xl mx-auto">
							How we've helped businesses maintain seamless operations.
						</p>
					</div>

					<div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-6xl mx-auto">
						{/* Case Study 1 */}
						<div className="bg-gray-50 rounded-xl overflow-hidden shadow-md">
							<Image
								src="https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80"
								alt="Fashion Retailer Case Study"
								className="w-full h-48 object-cover"
								width={500}
								height={300}
							/>
							<div className="p-6">
								<h3 className="text-xl font-bold mb-2">Fashion Retailer</h3>
								<p className="text-gray-600 mb-4">
									Reduced downtime by 92% and eliminated checkout errors during peak season with our Enterprise support
									plan.
								</p>
								<a href="#" className="text-blue-600 font-medium hover:text-blue-800">
									Read Case Study →
								</a>
							</div>
						</div>

						{/* Case Study 2 */}
						<div className="bg-gray-50 rounded-xl overflow-hidden shadow-md">
							<Image
								src="https://images.unsplash.com/photo-1556742044-3c52d6e88c62?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80"
								alt="Home Goods Store Case Study"
								className="w-full h-48 object-cover"
								width={500}
								height={300}
							/>
							<div className="p-6">
								<h3 className="text-xl font-bold mb-2">Home Goods Store</h3>
								<p className="text-gray-600 mb-4">
									Prevented a security breach through our proactive monitoring and patch management.
								</p>
								<a href="#" className="text-blue-600 font-medium hover:text-blue-800">
									Read Case Study →
								</a>
							</div>
						</div>

						{/* Case Study 3 */}
						<div className="bg-gray-50 rounded-xl overflow-hidden shadow-md">
							<Image
								src="https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80"
								alt="B2B Industrial Supplier Case Study"
								className="w-full h-48 object-cover"
								width={500}
								height={300}
							/>
							<div className="p-6">
								<h3 className="text-xl font-bold mb-2">B2B Industrial Supplier</h3>
								<p className="text-gray-600 mb-4">
									Improved site speed by 58% through our ongoing performance optimization services.
								</p>
								<a href="#" className="text-blue-600 font-medium hover:text-blue-800">
									Read Case Study →
								</a>
							</div>
						</div>
					</div>
				</div>
			</section>

			{/* FAQ Section */}
			<section className="py-20 bg-gray-50">
				<div className="container mx-auto px-4">
					<div className="max-w-4xl mx-auto">
						<div className="text-center mb-16">
							<h2 className="text-3xl md:text-4xl font-bold mb-4">Support & Maintenance FAQs</h2>
							<p className="text-xl text-gray-600">Answers to common questions about our support services.</p>
						</div>

						<div className="space-y-4">
							{/* FAQ Item 1 */}
							<div className="border border-gray-200 rounded-lg overflow-hidden">
								<button className="faq-toggle w-full flex justify-between items-center p-6 text-left focus:outline-none">
									<h3 className="text-lg font-medium text-gray-900">What's included in your monthly maintenance?</h3>
									<FaChevronDown className="text-blue-600 transition-transform duration-200" />
								</button>
								<div className="faq-content hidden px-6 pb-6">
									<p className="text-gray-600">
										Our monthly maintenance includes: security updates, plugin/theme/core updates (with testing),
										performance optimization, database maintenance, backup verification, security scans, and uptime
										monitoring. Higher-tier plans include additional services like content updates and more extensive
										optimizations.
									</p>
								</div>
							</div>

							{/* FAQ Item 2 */}
							<div className="border border-gray-200 rounded-lg overflow-hidden">
								<button className="faq-toggle w-full flex justify-between items-center p-6 text-left focus:outline-none">
									<h3 className="text-lg font-medium text-gray-900">How do you handle emergency issues after hours?</h3>
									<FaChevronDown className="text-blue-600 transition-transform duration-200" />
								</button>
								<div className="faq-content hidden px-6 pb-6">
									<p className="text-gray-600">
										We provide 24/7 emergency support for critical issues (store down, checkout broken, etc.). Our team
										rotates on-call duties to ensure immediate response. After-hours emergencies can be reported via our
										dedicated emergency phone line or priority support ticketing system.
									</p>
								</div>
							</div>

							{/* FAQ Item 3 */}
							<div className="border border-gray-200 rounded-lg overflow-hidden">
								<button className="faq-toggle w-full flex justify-between items-center p-6 text-left focus:outline-none">
									<h3 className="text-lg font-medium text-gray-900">
										Do you provide support for third-party apps and plugins?
									</h3>
									<FaChevronDown className="text-blue-600 transition-transform duration-200" />
								</button>
								<div className="faq-content hidden px-6 pb-6">
									<p className="text-gray-600">
										Yes, we support all standard third-party apps and plugins. For highly specialized or custom-built
										solutions, we may need to coordinate with the original developers. We handle updates, compatibility
										issues, and troubleshooting for all supported plugins.
									</p>
								</div>
							</div>

							{/* FAQ Item 4 */}
							<div className="border border-gray-200 rounded-lg overflow-hidden">
								<button className="faq-toggle w-full flex justify-between items-center p-6 text-left focus:outline-none">
									<h3 className="text-lg font-medium text-gray-900">Can we request specific maintenance windows?</h3>
									<FaChevronDown className="text-blue-600 transition-transform duration-200" />
								</button>
								<div className="faq-content hidden px-6 pb-6">
									<p className="text-gray-600">
										Absolutely. We schedule all maintenance during your specified low-traffic periods whenever possible.
										For Enterprise clients, we provide a maintenance calendar 30 days in advance and accommodate special
										requests for high-traffic periods like holidays.
									</p>
								</div>
							</div>

							{/* FAQ Item 5 */}
							<div className="border border-gray-200 rounded-lg overflow-hidden">
								<button className="faq-toggle w-full flex justify-between items-center p-6 text-left focus:outline-none">
									<h3 className="text-lg font-medium text-gray-900">
										How quickly can you restore from backup if something goes wrong?
									</h3>
									<FaChevronDown className="text-blue-600 transition-transform duration-200" />
								</button>
								<div className="faq-content hidden px-6 pb-6">
									<p className="text-gray-600">
										Our standard recovery time is under 2 hours for critical failures. We maintain multiple backup
										points (daily, weekly, monthly) with offsite storage. For Enterprise clients with mission-critical
										stores, we offer 1-hour recovery SLA with redundant systems in place.
									</p>
								</div>
							</div>

							{/* FAQ Item 6 */}
							<div className="border border-gray-200 rounded-lg overflow-hidden">
								<button className="faq-toggle w-full flex justify-between items-center p-6 text-left focus:outline-none">
									<h3 className="text-lg font-medium text-gray-900">What platforms do you support?</h3>
									<FaChevronDown className="text-blue-600 transition-transform duration-200" />
								</button>
								<div className="faq-content hidden px-6 pb-6">
									<p className="text-gray-600">
										We specialize in Shopify Plus, Magento (1 & 2), WooCommerce, and BigCommerce. We also support custom
										and headless implementations. Our team is certified on all major platforms and stays current with
										the latest updates and best practices.
									</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>

			<section className="py-20 bg-blue-600 text-white">
				<div className="container mx-auto px-4">
					<div className="max-w-4xl mx-auto text-center">
						<h2 className="text-3xl md:text-4xl font-bold mb-6">Ready for Stress-Free eCommerce Support?</h2>
						<p className="text-xl text-blue-100 mb-8 max-w-3xl mx-auto">
							Focus on growing your business while we handle the technical details. Get started with a free support
							consultation.
						</p>
						<div className="flex flex-col sm:flex-row justify-center space-y-4 sm:space-y-0 sm:space-x-4">
							<Link
								href="/contact#contact-form"
								className="bg-white text-blue-600 px-6 py-3 rounded-md font-medium hover:bg-gray-100 transition text-center"
							>
								Get Free Consultation
							</Link>
							<a
								href="tel:+18005551234"
								className="flex border-2 border-white text-white px-6 py-3 rounded-md font-medium hover:bg-white hover:text-blue-600 transition text-center"
							>
								<FaPhoneAlt className="mr-2" /> Call Support Team
							</a>
						</div>
					</div>
				</div>
			</section>
		</>
	);
}
