import Head from 'next/head';
import React from 'react';
import {FaArrowLeft} from 'react-icons/fa';
import {FaCheckCircle} from 'react-icons/fa';
import {FaTwitter, FaLinkedinIn, FaEnvelope} from 'react-icons/fa';
import {FaArrowRight} from 'react-icons/fa';

export default function BlogDetailsPage() {
	const articles = [
		{
			title: 'The Complete Guide to Shopify Plus Migration',
			date: 'May 28, 2023',
			readTime: '6 min read',
			image:
				'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80',
			link: 'blog-post.html',
		},
		{
			title: "10 Proven CRO Strategies That Boosted Our Clients' Sales",
			date: 'May 10, 2023',
			readTime: '10 min read',
			image:
				'https://images.unsplash.com/photo-1556742044-3c52d6e88c62?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80',
			link: 'blog-post.html',
		},
		{
			title: 'Why Mobile Commerce is Dominating in 2023',
			date: 'April 22, 2023',
			readTime: '7 min read',
			image:
				'https://images.unsplash.com/photo-1556742044-3c52d6e88c62?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80',
			link: 'blog-post.html',
		},
	];
	return (
		<>
			<Head>
				<title>Blog Details</title>
				<meta name="description" content="Generated by create next app" />
			</Head>

			{/* Blog header */}
			<section className="py-16 bg-white">
				<div className="container mx-auto px-4">
					<div className="max-w-4xl mx-auto">
						<div className="mb-6">
							<a href="/blog" className="text-indigo-600 hover:text-indigo-800 flex items-center">
								<FaArrowLeft className="mr-2" />
								Back to Blog
							</a>
						</div>

						<div className="flex items-center text-sm text-gray-500 mb-4">
							<span>June 15, 2023</span>
							<span className="mx-2">•</span>
							<span>8 min read</span>
							<span className="mx-2">•</span>
							<span className="text-indigo-600">Trends</span>
						</div>

						<h1 className="text-3xl md:text-4xl font-bold mb-6">Top eCommerce Trends to Watch in 2023</h1>

						<div className="flex items-center mb-8">
							<img
								src="https://randomuser.me/api/portraits/women/44.jpg"
								alt="Sarah Johnson"
								className="w-12 h-12 rounded-full mr-4"
							/>
							<div>
								<h4 className="font-bold">Sarah Johnson</h4>
								<p className="text-gray-600 text-sm">eCommerce Strategist at EcomReflex</p>
							</div>
						</div>

						<div className="relative h-96 rounded-xl overflow-hidden mb-8">
							<img
								src="https://images.unsplash.com/photo-1522071820081-009f0129c71c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80"
								alt="eCommerce Trends"
								className="w-full h-full object-cover"
							/>
						</div>

						<div className="flex flex-wrap gap-2 mb-8">
							<span className="tag">Trends</span>
							<span className="tag">Strategy</span>
							<span className="tag">Innovation</span>
							<span className="tag">2023</span>
						</div>
					</div>
				</div>
			</section>

			{/* Blog content */}
			<section className="py-12 bg-white">
				<div className="container mx-auto px-4">
					<div className="max-w-2xl mx-auto article-content">
						<p className="text-lg font-medium mb-6">
							The eCommerce landscape continues to evolve at a rapid pace, with new technologies and consumer behaviors
							shaping how brands sell online. As we move through 2023, several key trends are emerging that
							forward-thinking retailers should pay attention to. In this comprehensive guide, we'll explore the most
							important developments and how you can adapt your strategy to stay ahead.
						</p>

						<h2>1. AI-Powered Personalization Goes Mainstream</h2>

						<p>
							Artificial intelligence is transforming how eCommerce businesses personalize the shopping experience.
							Unlike basic recommendation engines of the past, today's AI solutions can analyze hundreds of data points
							in real-time to deliver hyper-relevant product suggestions, content, and offers.
						</p>

						<blockquote className="border-l-4 border-indigo-500 pl-4 italic my-4">
							"By 2023, retailers using AI personalization will see a 25% increase in revenue per visitor compared to
							those that don't." - Gartner Research
						</blockquote>

						<p>Key implementations to consider:</p>

						<ul className="list-disc list-inside space-y-2">
							<li>
								<strong>Dynamic product recommendations</strong> based on browsing behavior, purchase history, and
								similar customer profiles
							</li>
							<li>
								<strong>Personalized search results</strong> that understand user intent and context
							</li>
							<li>
								<strong>AI-generated content</strong> like custom product descriptions tailored to individual shoppers
							</li>
							<li>
								<strong>Predictive merchandising</strong> that automatically adjusts inventory displays based on demand
								signals
							</li>
						</ul>

						<div className="my-8 p-6 bg-indigo-50 rounded-lg">
							<h3 className="text-xl font-bold mb-3">Implementation Tip:</h3>
							<p>
								Start small with one area of personalization (like product recommendations) and measure impact before
								expanding. Many Shopify and Magento plugins now offer affordable AI capabilities without requiring
								custom development.
							</p>
						</div>

						<h2>2. Social Commerce Matures Beyond Simple Shoppable Posts</h2>

						<p>
							Social platforms are becoming full-fledged shopping destinations, with Instagram, TikTok, and Pinterest
							leading the charge. In 2023, we're seeing three key developments:
						</p>

						<h3>Live Shopping Events</h3>
						<p>
							Platforms are investing heavily in live video shopping features that combine entertainment with instant
							purchasing. Brands that create engaging, interactive live shopping experiences are seeing conversion rates
							3-5x higher than traditional social posts.
						</p>

						<h3>Augmented Reality Try-Ons</h3>
						<p>
							AR technology now allows customers to virtually "try on" products from makeup to furniture. Shopify's AR
							Quick Look feature has made this accessible to brands of all sizes, with early adopters seeing a 25%
							reduction in returns.
						</p>

						<h3>Social-First Product Development</h3>
						<p>
							Forward-thinking brands are now designing products specifically for social virality, with packaging and
							features optimized for unboxing videos and shareable moments.
						</p>

						<h2>3. Sustainability Becomes a Competitive Advantage</h2>

						<p>
							Consumers increasingly factor sustainability into purchasing decisions, with 65% saying they prefer to buy
							from purpose-driven brands (Nielsen). In 2023, sustainability efforts need to go beyond token gestures to
							become core to your value proposition.
						</p>

						<div className="my-8">
							<img
								src="https://images.unsplash.com/photo-1556760544-74068565f05c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80"
								alt="Sustainable Packaging"
								className="w-full rounded-lg"
							/>
							<p className="text-sm text-gray-500 mt-2 text-center">
								Sustainable packaging options are now expected by many consumers
							</p>
						</div>

						<p>Key areas to focus on:</p>

						<ul className="list-disc list-inside space-y-2">
							<li>
								<strong>Carbon-neutral shipping</strong> options at checkout
							</li>
							<li>
								<strong>Product lifecycle transparency</strong> with detailed sourcing and manufacturing information
							</li>
							<li>
								<strong>Circular commerce models</strong> like resale, rental, and refurbishment programs
							</li>
							<li>
								<strong>Eco-friendly packaging</strong> that minimizes waste without compromising unboxing experience
							</li>
						</ul>

						<h2>4. Headless Commerce Enables Truly Omnichannel Experiences</h2>

						<p>
							The headless commerce architecture (decoupling frontend presentation from backend commerce functionality)
							is moving from early adopter to mainstream in 2023. This approach provides two key advantages:
						</p>

						<ol className="list-decimal list-inside space-y-2">
							<li>
								<strong>Flexibility to create unique brand experiences</strong> across any touchpoint (web, mobile, IoT,
								in-store kiosks)
							</li>
							<li>
								<strong>Future-proof technology stack</strong> that can adapt as new channels emerge without requiring
								complete replatforming
							</li>
						</ol>

						<p>
							While headless requires more technical investment upfront, the long-term benefits for growing brands are
							becoming undeniable. Platforms like Shopify Hydrogen and BigCommerce's headless solutions are making this
							architecture more accessible.
						</p>

						<h2>5. B2B eCommerce Catches Up to B2C Standards</h2>

						<p>
							Business buyers now expect the same seamless, intuitive experiences they get as consumers. In 2023, B2B
							eCommerce is undergoing a transformation with:
						</p>

						<ul className="list-disc list-inside space-y-2">
							<li>
								<strong>Self-service portals</strong> with personalized pricing and catalogs
							</li>
							<li>
								<strong>AI-powered search</strong> that understands industry terminology and part numbers
							</li>
							<li>
								<strong>Mobile-optimized purchasing workflows</strong> for buyers on the go
							</li>
							<li>
								<strong>Integration with procurement systems</strong> like SAP and Oracle
							</li>
						</ul>

						<p>
							The lines between B2B and B2C commerce continue to blur, creating opportunities for brands that can
							deliver exceptional digital buying experiences to all customer types.
						</p>

						<h2>Key Takeaways for 2023</h2>

						<p>As you evaluate your eCommerce strategy for the remainder of 2023, focus on these priorities:</p>

						<ul className="space-y-2">
							<li className="flex items-center">
								<FaCheckCircle className="text-green-500 mr-2" /> Implement AI-driven personalization at scale
							</li>
							<li className="flex items-center">
								<FaCheckCircle className="text-green-500 mr-2" /> Develop a social commerce strategy beyond basic
								shoppable posts
							</li>
							<li className="flex items-center">
								<FaCheckCircle className="text-green-500 mr-2" /> Make sustainability a core part of your brand story
								and operations
							</li>
							<li className="flex items-center">
								<FaCheckCircle className="text-green-500 mr-2" /> Evaluate if headless architecture could benefit your
								omnichannel goals
							</li>
							<li className="flex items-center">
								<FaCheckCircle className="text-green-500 mr-2" /> Bring B2B buying experiences up to B2C standards
							</li>
						</ul>

						<p className="mt-6">
							The most successful eCommerce brands in 2023 will be those that strategically adopt these trends while
							maintaining focus on their core customer experience. Rather than chasing every new development, identify
							the 2-3 trends that align best with your business objectives and customer needs.
						</p>
					</div>
				</div>
			</section>

			{/* blog bio */}
			<section className="py-12 bg-gray-50">
				<div className="container mx-auto px-4">
					<div className="max-w-2xl mx-auto">
						<div className="bg-white p-8 rounded-xl shadow-sm">
							<div className="flex flex-col md:flex-row items-center">
								<img
									src="https://randomuser.me/api/portraits/women/44.jpg"
									alt="Sarah Johnson"
									className="w-24 h-24 rounded-full mb-4 md:mb-0 md:mr-6"
								/>
								<div>
									<h3 className="text-xl font-bold mb-2">About the Author</h3>
									<p className="text-gray-600 mb-4">
										Sarah Johnson is an eCommerce Strategist at EcomReflex with over 10 years of experience helping
										brands optimize their online sales. She specializes in conversion rate optimization and emerging
										retail technologies.
									</p>
									<div className="flex justify-center md:justify-start space-x-4 text-indigo-600 text-xl">
										<a href="#" aria-label="Twitter">
											<FaTwitter />
										</a>
										<a href="#" aria-label="LinkedIn">
											<FaLinkedinIn />
										</a>
										<a href="mailto:sarah@example.com" aria-label="Email">
											<FaEnvelope />
										</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>

			{/* Related Posts */}
			<section className="py-20 bg-white">
				<div className="container mx-auto px-4">
					<div className="text-center mb-16">
						<h2 className="text-3xl md:text-4xl font-bold mb-4">You Might Also Like</h2>
						<p className="text-xl text-gray-600 max-w-3xl mx-auto">
							More insights to help grow your eCommerce business
						</p>
					</div>

					<div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-6xl mx-auto">
						{articles.map((article, index) => (
							<div key={index} className="related-article bg-white rounded-xl shadow-md overflow-hidden">
								<div className="relative h-48 overflow-hidden">
									<img src={article.image} alt={article.title} className="w-full h-full object-cover" />
								</div>
								<div className="p-6">
									<div className="flex items-center text-sm text-gray-500 mb-3">
										<span>{article.date}</span>
										<span className="mx-2">•</span>
										<span>{article.readTime}</span>
									</div>
									<h3 className="text-xl font-bold mb-3">{article.title}</h3>
									<a
										href={article.link}
										className="text-indigo-600 font-medium hover:text-indigo-800 flex items-center"
									>
										Read more <FaArrowRight className="ml-2" />
									</a>
								</div>
							</div>
						))}
					</div>
				</div>
			</section>

			{/* Newsletter */}
			<section className="py-20 bg-indigo-600 text-white">
				<div className="container mx-auto px-4">
					<div className="max-w-3xl mx-auto text-center">
						<h2 className="text-3xl md:text-4xl font-bold mb-6">Get eCommerce Insights Delivered to Your Inbox</h2>
						<p className="text-xl text-indigo-100 mb-8">
							Join 10,000+ eCommerce professionals who receive our weekly newsletter with the latest trends, tips, and
							strategies.
						</p>
						<form className="flex flex-col sm:flex-row gap-4 max-w-md mx-auto">
							<input
								type="email"
								placeholder="Your email address"
								className="flex-grow px-4 py-3 bg-white border border-white rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-300 text-gray-900 placeholder:text-indigo-200"
							/>
							<button
								type="submit"
								className="bg-white text-indigo-600 px-6 py-3 rounded-md font-medium hover:bg-gray-100 transition"
							>
								Subscribe
							</button>
						</form>
						<p className="text-sm text-indigo-200 mt-4">We respect your privacy. Unsubscribe at any time.</p>
					</div>
				</div>
			</section>
		</>
	);
}
