import Head from 'next/head';
import React from 'react';

export default function PlatformMigrationPage() {
	return (
		<>
			<Head>
				<title>Services</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
		</>
	);
}
