import Head from 'next/head';
import Link from 'next/link';
import React from 'react';
import {
	FaBiking,
	FaBoxes,
	FaChartLine,
	FaDownload,
	FaExclamationTriangle,
	FaLightbulb,
	FaMapMarked,
	FaMapMarkedAlt,
	FaMapMarkerAlt,
	FaProjectDiagram,
	FaRegCalendarAlt,
} from 'react-icons/fa';
import {FaExclamation} from 'react-icons/fa';
import {FaChartBar, FaStar} from 'react-icons/fa';
import {FaUtensils, FaCashRegister, FaCloud, FaPlug, FaChartPie, FaMobileAlt} from 'react-icons/fa';

export default function CaseStudiesDetailPage() {
	return (
		<>
			<Head>
				<title>Case Studies</title>
				<meta name="description" content="Generated by create next app" />
			</Head>

			<section className="hero-gradient text-white">
				<div className="container mx-auto px-4 py-20 md:py-28">
					<div className="max-w-4xl mx-auto text-center">
						<span className="solution-tag bg-white text-indigo-600 mb-4">Food Delivery + ePOS</span>
						<h1 className="text-4xl md:text-5xl font-bold leading-tight mb-6">
							UrbanEats: Cloud Kitchen Transformation
						</h1>
						<p className="text-xl text-indigo-100 mb-8">
							How a delivery-only restaurant scaled operations with 220% revenue growth
						</p>
						<div className="flex justify-center">
							<div className="inline-flex items-center bg-indigo-700 bg-opacity-50 rounded-full px-6 py-2">
								<i className="fas fa-industry mr-2"></i>
								<span>Food & Beverage</span>
							</div>
						</div>
					</div>
				</div>
			</section>

			<section className="py-16 bg-white">
				<div className="container mx-auto px-4">
					<div className="flex flex-col lg:flex-row gap-12 max-w-6xl mx-auto">
						<div className="lg:w-2/3">
							<div className="mb-16">
								<h2 className="text-3xl font-bold mb-6">Overview</h2>
								<div className="prose max-w-none">
									<p className="text-gray-600 mb-4">
										UrbanEats operates a delivery-only cloud kitchen in Chicago, serving three distinct virtual brands
										from a single physical location. As their popularity grew across multiple delivery platforms, they
										faced increasing operational complexity that threatened their ability to scale.
									</p>
									<p className="text-gray-600">
										NexaSuite implemented an integrated solution combining our Food Delivery Platform with mPOS and
										Cloud Kitchen Management tools, enabling UrbanEats to triple their order volume while reducing
										operational friction.
									</p>
								</div>
							</div>

							<div className="mb-16">
								<div className="flex items-center mb-6">
									<div className="challenge-icon rounded-lg p-3 mr-4">
										<FaExclamationTriangle className="text-2xl" />
										{/* <i className="fas fa-exclamation-triangle text-2xl"></i> */}
									</div>
									<h2 className="text-3xl font-bold">The Challenge</h2>
								</div>
								<div className="prose max-w-none">
									<p className="text-gray-600 mb-6">
										UrbanEats was experiencing growing pains from their rapid success. Their existing patchwork of
										systems created significant inefficiencies:
									</p>
									<ul className="space-y-4 mb-6">
										<li className="flex items-start">
											<div className="bg-red-100 rounded-full p-2 mr-4">
												<FaExclamation className="text-red-600" />
											</div>
											<div>
												<h4 className="font-bold mb-1">Disconnected Operations</h4>
												<p className="text-gray-600">
													Separate systems for orders (Uber Eats, DoorDash, Grubhub), inventory (spreadsheets), and
													kitchen operations (paper tickets) led to constant reconciliation errors.
												</p>
											</div>
										</li>
										<li className="flex items-start">
											<div className="bg-red-100 rounded-full p-2 mr-4">
												<FaExclamation className="text-red-600" />
											</div>
											<div>
												<h4 className="font-bold mb-1">Delivery Coordination Chaos</h4>
												<p className="text-gray-600">
													Drivers from multiple platforms crowded the pickup area while kitchen staff struggled to
													prioritize orders based on delivery ETAs.
												</p>
											</div>
										</li>
										<li className="flex items-start">
											<div className="bg-red-100 rounded-full p-2 mr-4">
												<FaExclamation className="text-red-600" />
											</div>
											<div>
												<h4 className="font-bold mb-1">Inventory Waste</h4>
												<p className="text-gray-600">
													With no cross-brand visibility, ingredients would run out for one brand while going unused for
													others, resulting in 30% waste.
												</p>
											</div>
										</li>
										<li className="flex items-start">
											<div className="bg-red-100 rounded-full p-2 mr-4">
												<FaExclamation className="text-red-600" />
											</div>
											<div>
												<h4 className="font-bold mb-1">Limited Growth Potential</h4>
												<p className="text-gray-600">
													The manual processes couldn't support additional brands or locations without proportional
													staff increases.
												</p>
											</div>
										</li>
									</ul>
									<div className="bg-gray-50 rounded-xl p-6 border-l-4 border-red-500">
										<h4 className="font-bold text-lg mb-2">Critical Pain Point</h4>
										<p className="text-gray-600">
											"During peak hours, we had 15-20 drivers waiting while our kitchen fell behind. Customers received
											cold food, and our ratings were dropping. We knew we needed a complete operational overhaul."
											<span className="block font-medium mt-2">— Sarah Chen, COO</span>
										</p>
									</div>
								</div>
							</div>

							<div className="mb-16">
								<div className="flex items-center mb-6">
									<div className="solution-icon rounded-lg p-3 mr-4">
										<FaLightbulb className="text-2xl" />
									</div>
									<h2 className="text-3xl font-bold">The Solution</h2>
								</div>
								<div className="prose max-w-none">
									<p className="text-gray-600 mb-6">
										NexaSuite implemented a comprehensive solution tailored to UrbanEats' multi-brand cloud kitchen
										operation:
									</p>

									<div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
										<div className="bg-blue-50 p-6 rounded-lg border border-blue-100">
											<div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center mb-4">
												<FaProjectDiagram className="text-blue-600" />
											</div>
											<h4 className="font-bold mb-2">Unified Operations Hub</h4>
											<p className="text-gray-600">
												Single dashboard integrating all delivery platforms with real-time order aggregation and
												prioritization
											</p>
										</div>
										<div className="bg-blue-50 p-6 rounded-lg border border-blue-100">
											<div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center mb-4">
												<FaBoxes className="text-blue-600" />
											</div>
											<h4 className="font-bold mb-2">Smart Inventory System</h4>
											<p className="text-gray-600">
												Cross-brand ingredient tracking with automated low-stock alerts and suggested substitutions
											</p>
										</div>
										<div className="bg-blue-50 p-6 rounded-lg border border-blue-100">
											<div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center mb-4">
												<FaBiking className="text-blue-600" />
											</div>
											<h4 className="font-bold mb-2">Delivery Orchestration</h4>
											<p className="text-gray-600">
												Driver staging system with automated notifications and optimized pickup sequencing
											</p>
										</div>
										<div className="bg-blue-50 p-6 rounded-lg border border-blue-100">
											<div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center mb-4">
												<FaChartLine className="text-blue-600" />
											</div>
											<h4 className="font-bold mb-2">Performance Analytics</h4>
											<p className="text-gray-600">
												Brand-by-brand metrics with profitability analysis and menu optimization suggestions
											</p>
										</div>
									</div>

									<h3 className="text-2xl font-bold mb-4">Implementation Process</h3>
									<div className="mb-8">
										<div className="space-y-8">
											<div className="timeline-item">
												<h5 className="font-bold mb-2">Phase 1: Discovery & Planning (2 weeks)</h5>
												<ul className="list-disc pl-5 text-gray-600 space-y-2">
													<li>Comprehensive workflow analysis</li>
													<li>Integration requirements mapping</li>
													<li>Customization planning for multi-brand support</li>
												</ul>
											</div>
											<div className="timeline-item">
												<h5 className="font-bold mb-2">Phase 2: System Setup (3 weeks)</h5>
												<ul className="list-disc pl-5 text-gray-600 space-y-2">
													<li>Menu migration and categorization</li>
													<li>Staff training on new workflows</li>
													<li>Inventory system initialization</li>
												</ul>
											</div>
											<div className="timeline-item">
												<h5 className="font-bold mb-2">Phase 3: Delivery Integration (2 weeks)</h5>
												<ul className="list-disc pl-5 text-gray-600 space-y-2">
													<li>Connected Uber Eats, DoorDash, and Grubhub APIs</li>
													<li>Driver staging area setup</li>
													<li>Automated notification system configuration</li>
												</ul>
											</div>
											<div className="timeline-item">
												<h5 className="font-bold mb-2">Phase 4: Go Live & Optimization (3 weeks)</h5>
												<ul className="list-disc pl-5 text-gray-600 space-y-2">
													<li>Phased rollout with performance monitoring</li>
													<li>Staff feedback incorporation</li>
													<li>Continuous improvement adjustments</li>
												</ul>
											</div>
										</div>
									</div>

									<div className="bg-gray-50 rounded-xl p-6 border-l-4 border-blue-500">
										<h4 className="font-bold text-lg mb-2">Key Implementation Insight</h4>
										<p className="text-gray-600">
											"We scheduled the final go-live for a Tuesday, traditionally their slowest day. This allowed staff
											to get comfortable with the system before weekend rushes. By the second week, they were handling
											30% more orders with less stress."
											<span className="block font-medium mt-2">— Mark Williams, NexaSuite Implementation Lead</span>
										</p>
									</div>
								</div>
							</div>

							<div className="mb-16">
								<div className="flex items-center mb-6">
									<div className="result-icon rounded-lg p-3 mr-4">
										<FaChartBar className="text-2xl" />
									</div>
									<h2 className="text-3xl font-bold">The Results</h2>
								</div>
								<div className="prose max-w-none">
									<p className="text-gray-600 mb-8">
										Within six months of implementation, UrbanEats achieved dramatic improvements across all operational
										metrics:
									</p>

									<div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
										<div className="stat-card bg-green-50 p-6 rounded-lg border border-green-100 text-center">
											<div className="text-4xl font-bold mb-2 text-green-600">220%</div>
											<h4 className="font-bold mb-2">Revenue Growth</h4>
											<p className="text-gray-600">
												Increased monthly revenue from $85k to $272k through expanded capacity and reduced order
												declines.
											</p>
										</div>
										<div className="stat-card bg-green-50 p-6 rounded-lg border border-green-100 text-center">
											<div className="text-4xl font-bold mb-2 text-green-600">45%</div>
											<h4 className="font-bold mb-2">Waste Reduction</h4>
											<p className="text-gray-600">
												Decreased ingredient costs through optimized cross-brand utilization and automated ordering.
											</p>
										</div>
										<div className="stat-card bg-green-50 p-6 rounded-lg border border-green-100 text-center">
											<div className="text-4xl font-bold mb-2 text-green-600">4.7★</div>
											<h4 className="font-bold mb-2">Customer Rating</h4>
											<p className="text-gray-600">
												Improved from 3.8★ through faster, more accurate deliveries and better food quality.
											</p>
										</div>
										<div className="stat-card bg-green-50 p-6 rounded-lg border border-green-100 text-center">
											<div className="text-4xl font-bold mb-2 text-green-600">12 min</div>
											<h4 className="font-bold mb-2">Avg. Delivery Time</h4>
											<p className="text-gray-600">
												Reduced from 22 minutes through optimized driver staging and kitchen prioritization.
											</p>
										</div>
									</div>

									<h3 className="text-2xl font-bold mb-4">Long-Term Impact</h3>
									<p className="text-gray-600 mb-6">
										The operational efficiencies enabled by NexaSuite allowed UrbanEats to:
									</p>
									<ul className="list-disc pl-5 text-gray-600 space-y-2 mb-6">
										<li>Expand to two additional locations with the same management overhead.</li>
										<li>Launch a fourth virtual brand targeting health-conscious consumers.</li>
										<li>Reduce kitchen staff turnover by 60% through less stressful workflows.</li>
										<li>Implement dynamic pricing that increased margins by 8% during peak hours.</li>
									</ul>

									<div className="bg-gray-50 rounded-xl p-6 border-l-4 border-green-500">
										<h4 className="font-bold text-lg mb-2">Client Perspective</h4>
										<p className="text-gray-600">
											"NexaSuite didn't just solve our immediate problems—it completely transformed how we think about
											our business. The data insights helped us identify that one of our virtual brands was actually
											losing money despite high sales. We repositioned it and turned it into our second most profitable
											concept."
											<span className="block font-medium mt-2">— Sarah Chen, COO</span>
										</p>
										<div className="mt-4 flex text-yellow-400">
											<FaStar />
											<FaStar />
											<FaStar />
											<FaStar />
											<FaStar />
										</div>
									</div>
								</div>
							</div>

							<div className="mb-16">
								<h2 className="text-3xl font-bold mb-6">Technologies Used</h2>
								<div className="grid grid-cols-2 md:grid-cols-3 gap-4 mb-6">
									<div className="bg-gray-50 p-4 rounded-lg flex items-center">
										<div className="w-10 h-10 bg-purple-100 rounded-lg flex items-center justify-center mr-4">
											<FaUtensils className="text-purple-600 text-2xl" />
										</div>
										<span className="font-medium">Food Delivery Platform</span>
									</div>
									<div className="bg-gray-50 p-4 rounded-lg flex items-center">
										<div className="w-10 h-10 bg-blue-100 rounded-lg flex items-center justify-center mr-4">
											<FaCashRegister className="text-blue-600 text-2xl" />
										</div>
										<span className="font-medium">mPOS System</span>
									</div>
									<div className="bg-gray-50 p-4 rounded-lg flex items-center">
										<div className="w-10 h-10 bg-pink-100 rounded-lg flex items-center justify-center mr-4">
											<FaCloud className="text-pink-600 text-2xl" />
										</div>
										<span className="font-medium">Cloud Kitchen Tools</span>
									</div>
									<div className="bg-gray-50 p-4 rounded-lg flex items-center">
										<div className="w-10 h-10 bg-teal-100 rounded-lg flex items-center justify-center mr-4">
											<FaPlug className="text-teal-600 text-2xl" />
										</div>
										<span className="font-medium">API Integrations</span>
									</div>
									<div className="bg-gray-50 p-4 rounded-lg flex items-center">
										<div className="w-10 h-10 bg-yellow-100 rounded-lg flex items-center justify-center mr-4">
											<FaChartPie className="text-yellow-600 text-2xl" />
										</div>
										<span className="font-medium">Advanced Analytics</span>
									</div>
									<div className="bg-gray-50 p-4 rounded-lg flex items-center">
										<div className="w-10 h-10 bg-red-100 rounded-lg flex items-center justify-center mr-4">
											<FaMobileAlt className="text-red-600 text-2xl" />
										</div>
										<span className="font-medium">Driver App</span>
									</div>
								</div>
							</div>

							<div className="mb-16">
								<h2 className="text-3xl font-bold mb-6">Gallery</h2>
								<div className="grid grid-cols-1 md:grid-cols-2 gap-6">
									<div className="bg-gray-100 rounded-lg overflow-hidden">
										<img
											src="https://images.unsplash.com/photo-1555396273-367ea4eb4db5?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80"
											alt="UrbanEats kitchen"
											className="w-full h-64 object-cover"
										/>
										<div className="p-4">
											<p className="text-gray-600 text-sm">UrbanEats kitchen staff using the unified display system</p>
										</div>
									</div>
									<div className="bg-gray-100 rounded-lg overflow-hidden">
										<img
											src="https://images.unsplash.com/photo-1559847844-5315695dadae?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80"
											alt="Delivery driver"
											className="w-full h-64 object-cover"
										/>
										<div className="p-4">
											<p className="text-gray-600 text-sm">Optimized driver staging area with digital notifications</p>
										</div>
									</div>
								</div>
							</div>

							<div className="bg-indigo-50 rounded-xl p-8 text-center">
								<h3 className="text-2xl font-bold mb-4">Ready to Transform Your Operations?</h3>
								<p className="text-gray-600 mb-6 max-w-2xl mx-auto">
									Discover how NexaSuite can help your food business achieve similar results
								</p>
								<div className="flex flex-col sm:flex-row justify-center space-y-4 sm:space-y-0 sm:space-x-4">
									<Link
										href="/get-started"
										className="bg-indigo-600 text-white px-6 py-3 rounded-md font-medium hover:bg-indigo-700 transition text-center"
									>
										Get Started
									</Link>
									<Link
										href="/case-studies"
										className="border-2 border-indigo-600 text-indigo-600 px-6 py-3 rounded-md font-medium hover:bg-indigo-600 hover:text-white transition text-center"
									>
										View More Case Studies
									</Link>
								</div>
							</div>
						</div>

						<div className="lg:w-1/3">
							<div className="sticky-sidebar space-y-6">
								<div className="bg-white rounded-xl shadow-md p-6">
									<h3 className="text-xl font-bold mb-4">Key Statistics</h3>
									<div className="space-y-4">
										<div className="flex justify-between border-b border-gray-100 pb-3">
											<span className="text-gray-600">Implementation Time</span>
											<span className="font-medium">8 weeks</span>
										</div>
										<div className="flex justify-between border-b border-gray-100 pb-3">
											<span className="text-gray-600">ROI Achieved</span>
											<span className="font-medium">6 months</span>
										</div>
										<div className="flex justify-between border-b border-gray-100 pb-3">
											<span className="text-gray-600">Order Volume</span>
											<span className="font-medium">3.2x increase</span>
										</div>
										<div className="flex justify-between border-b border-gray-100 pb-3">
											<span className="text-gray-600">Staff Efficiency</span>
											<span className="font-medium">35% improvement</span>
										</div>
										<div className="flex justify-between">
											<span className="text-gray-600">Customer Retention</span>
											<span className="font-medium">42% increase</span>
										</div>
									</div>
								</div>

								<div className="bg-white rounded-xl shadow-md p-6">
									<h3 className="text-xl font-bold mb-4">Client Profile</h3>
									<div className="flex items-center mb-4">
										<img
											src="https://images.unsplash.com/photo-1600880292203-757bb62b4baf?ixlib=rb-1.2.1&auto=format&fit=crop&w=200&q=80"
											alt="UrbanEats"
											className="w-16 h-16 rounded-full mr-4"
										/>
										<div>
											<h4 className="font-bold">UrbanEats</h4>
											<p className="text-gray-600">Cloud Kitchen Operator</p>
										</div>
									</div>
									<ul className="space-y-3">
										<li className="flex items-start">
											<FaMapMarkerAlt className="text-gray-400 mt-1 mr-3" />
											<i className="fas fa-map-marker-alt text-gray-400 mt-1 mr-3"></i>
											<span className="text-gray-600">Chicago, IL</span>
										</li>
										<li className="flex items-start">
											<FaUtensils className="text-gray-400 mt-1 mr-3" />
											<span className="text-gray-600">3 Virtual Brands</span>
										</li>
										<li className="flex items-start">
											<FaRegCalendarAlt className="text-gray-400 mt-1 mr-3" />
											<span className="text-gray-600">Implemented: March 2022</span>
										</li>
									</ul>
								</div>

								<div className="bg-white rounded-xl shadow-md p-6">
									<h3 className="text-xl font-bold mb-4">Download Full Case Study</h3>
									<p className="text-gray-600 mb-4">
										Get the complete UrbanEats case study with additional data and analysis.
									</p>
									<form className="space-y-4">
										<input
											type="text"
											placeholder="Your Name"
											className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
										/>
										<input
											type="email"
											placeholder="Email Address"
											className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
										/>
										<button
											type="submit"
											className="flex items-center justify-center w-full bg-indigo-600 text-white px-4 py-2 rounded-md hover:bg-indigo-700 transition"
										>
											Download PDF <FaDownload className="ml-2" />
										</button>
									</form>
								</div>

								<div className="bg-white rounded-xl shadow-md p-6">
									<h3 className="text-xl font-bold mb-4">Related Case Studies</h3>
									<div className="space-y-4">
										<a href="#" className="group flex items-start">
											<img
												src="https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?ixlib=rb-1.2.1&auto=format&fit=crop&w=100&q=80"
												alt="Retail POS"
												className="w-16 h-16 rounded-md object-cover mr-4"
											/>
											<div>
												<h4 className="font-bold group-hover:text-indigo-600 transition">
													StyleHub: Omnichannel Retail
												</h4>
												<p className="text-sm text-gray-600">ePOS/mPOS implementation</p>
											</div>
										</a>
										<a href="#" className="group flex items-start">
											<img
												src="https://images.unsplash.com/photo-1579389083078-4e7018379f7e?ixlib=rb-1.2.1&auto=format&fit=crop&w=100&q=80"
												alt="Booking System"
												className="w-16 h-16 rounded-md object-cover mr-4"
											/>
											<div>
												<h4 className="font-bold group-hover:text-indigo-600 transition">
													SpaRelax: Online Reservations
												</h4>
												<p className="text-sm text-gray-600">Booking system transformation</p>
											</div>
										</a>
										<a href="#" className="group flex items-start">
											<img
												src="https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?ixlib=rb-1.2.1&auto=format&fit=crop&w=100&q=80"
												alt="eCommerce"
												className="w-16 h-16 rounded-md object-cover mr-4"
											/>
											<div>
												<h4 className="font-bold group-hover:text-indigo-600 transition">
													CraftMarket: Global Expansion
												</h4>
												<p className="text-sm text-gray-600">eCommerce platform scaling</p>
											</div>
										</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
		</>
	);
}
