import Head from 'next/head';
import React from 'react';
import {FaEnvelope, FaCalendarCheck, FaFileAlt} from 'react-icons/fa';

export default function GetStartedPage() {
	const timelineSteps = [
		{
			id: 1,
			title: 'Week 1-2: Discovery & Planning',
			description: 'Requirements gathering, technical planning, and project roadmap development.',
		},
		{
			id: 2,
			title: 'Week 3-4: Design Phase',
			description: 'UI/UX design, wireframing, and prototyping with your feedback incorporated.',
		},
		{
			id: 3,
			title: 'Week 5-8: Development',
			description: 'Frontend and backend development with weekly demos and progress updates.',
		},
		{
			id: 4,
			title: 'Week 9: Testing & QA',
			description: 'Rigorous testing across devices, browsers, and user scenarios to ensure quality.',
		},
		{
			id: 5,
			title: 'Week 10: Launch & Training',
			description: 'Final deployment, performance optimization, and training for your team.',
		},
	];
	return (
		<>
			<Head>
				<title>Get Started</title>
				<meta name="description" content="Generated by create next app" />
			</Head>

			{/* Hero Section */}
			<section className="hero-gradient text-white">
				<div className="container mx-auto px-4 py-20 md:py-28">
					<div className="max-w-4xl mx-auto text-center">
						<h1 className="text-4xl md:text-5xl font-bold leading-tight mb-6">Ready to Launch Your eCommerce Store?</h1>
						<p className="text-xl text-indigo-100 mb-8">
							Follow our simple onboarding process to get your project started with EcomReflex. We'll guide you through
							each step to ensure your eCommerce success.
						</p>
						<div className="flex flex-col sm:flex-row justify-center space-y-4 sm:space-y-0 sm:space-x-4">
							<a
								href="#onboarding-steps"
								className="bg-white text-indigo-600 px-6 py-3 rounded-md font-medium hover:bg-gray-100 transition text-center"
							>
								See How It Works
							</a>
							<a
								href="#project-questionnaire"
								className="border-2 border-white text-white px-6 py-3 rounded-md font-medium hover:bg-white hover:text-indigo-600 transition text-center"
							>
								Start Your Project Now
							</a>
						</div>
					</div>
				</div>
			</section>

			{/* Onboarding Steps */}
			<section id="onboarding-steps" className="py-20 bg-white">
				<div className="container mx-auto px-4">
					<div className="text-center mb-16">
						<h2 className="text-3xl md:text-4xl font-bold mb-4">Our Simple Onboarding Process</h2>
						<p className="text-xl text-gray-600 max-w-3xl mx-auto">
							We've streamlined our process to get your project started quickly and efficiently.
						</p>
					</div>

					<div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-5xl mx-auto">
						{/* Step 1 */}
						<div className="step-card bg-gray-50 p-8 rounded-xl shadow-md text-center transition duration-300">
							<div className="w-20 h-20 bg-indigo-100 rounded-full flex items-center justify-center mb-6 mx-auto">
								<span className="text-indigo-600 font-bold text-2xl">1</span>
							</div>
							<h3 className="text-xl font-bold mb-3">Initial Consultation</h3>
							<p className="text-gray-600">
								Schedule a free 30-minute discovery call where we'll discuss your business goals, requirements, and
								expectations.
							</p>
						</div>

						{/* Step 2 */}
						<div className="step-card bg-gray-50 p-8 rounded-xl shadow-md text-center transition duration-300">
							<div className="w-20 h-20 bg-indigo-100 rounded-full flex items-center justify-center mb-6 mx-auto">
								<span className="text-indigo-600 font-bold text-2xl">2</span>
							</div>
							<h3 className="text-xl font-bold mb-3">Project Questionnaire</h3>
							<p className="text-gray-600">
								Complete our detailed project brief to help us understand your technical needs, design preferences, and
								timeline.
							</p>
						</div>

						{/* Step 3 */}
						<div className="step-card bg-gray-50 p-8 rounded-xl shadow-md text-center transition duration-300">
							<div className="w-20 h-20 bg-indigo-100 rounded-full flex items-center justify-center mb-6 mx-auto">
								<span className="text-indigo-600 font-bold text-2xl">3</span>
							</div>
							<h3 className="text-xl font-bold mb-3">Proposal & Agreement</h3>
							<p className="text-gray-600">
								We'll prepare a customized proposal with scope, timeline, and investment. Once approved, we'll finalize
								the contract.
							</p>
						</div>

						{/* Step 4 */}
						<div className="step-card bg-gray-50 p-8 rounded-xl shadow-md text-center transition duration-300">
							<div className="w-20 h-20 bg-indigo-100 rounded-full flex items-center justify-center mb-6 mx-auto">
								<span className="text-indigo-600 font-bold text-2xl">4</span>
							</div>
							<h3 className="text-xl font-bold mb-3">Kickoff Meeting</h3>
							<p className="text-gray-600">
								Meet your dedicated project team, review timelines, and establish communication protocols for your
								project.
							</p>
						</div>

						{/* Step 5 */}
						<div className="step-card bg-gray-50 p-8 rounded-xl shadow-md text-center transition duration-300">
							<div className="w-20 h-20 bg-indigo-100 rounded-full flex items-center justify-center mb-6 mx-auto">
								<span className="text-indigo-600 font-bold text-2xl">5</span>
							</div>
							<h3 className="text-xl font-bold mb-3">Project Initiation</h3>
							<p className="text-gray-600">
								We'll begin with discovery and planning, then move into design and development based on the approved
								roadmap.
							</p>
						</div>

						{/* Step 6 */}
						<div className="step-card bg-gray-50 p-8 rounded-xl shadow-md text-center transition duration-300">
							<div className="w-20 h-20 bg-indigo-100 rounded-full flex items-center justify-center mb-6 mx-auto">
								<span className="text-indigo-600 font-bold text-2xl">6</span>
							</div>
							<h3 className="text-xl font-bold mb-3">Regular Updates</h3>
							<p className="text-gray-600">
								Receive weekly progress reports, participate in review sessions, and provide feedback throughout the
								process.
							</p>
						</div>
					</div>
				</div>
			</section>

			{/* Timeline Section */}
			<section className="py-20 bg-gray-50">
				<div className="container mx-auto px-4">
					<div className="text-center mb-16">
						<h2 className="text-3xl md:text-4xl font-bold mb-4">Typical Project Timeline</h2>
						<p className="text-xl text-gray-600 max-w-3xl mx-auto">
							While each project is unique, here's what you can generally expect
						</p>
					</div>

					<div className="relative max-w-5xl mx-auto">
						<div className="hidden md:block absolute left-1/2 h-full w-1 bg-indigo-200 transform -translate-x-1/2"></div>
						<div className="flex flex-col gap-16">
							{timelineSteps.map((step, index) => (
								<div
									key={step.id}
									className={`relative flex flex-col md:flex-row items-center md:justify-between ${
										index % 2 === 0 ? 'md:flex-row' : 'md:flex-row-reverse'
									}`}
								>
									<div className="w-full md:w-5/12">
										<div className="bg-white p-6 rounded-lg shadow-md">
											<h3 className="text-xl font-bold mb-2 text-indigo-600">{step.title}</h3>
											<p className="text-gray-600">{step.description}</p>
										</div>
									</div>
									<div className="hidden md:flex md:w-2/12 justify-center">
										<div className="w-12 h-12 bg-indigo-600 rounded-full flex items-center justify-center">
											<span className="text-white font-bold">{step.id}</span>
										</div>
									</div>
									<div className="md:hidden mt-4">
										<div className="w-12 h-12 bg-indigo-600 rounded-full flex items-center justify-center mx-auto">
											<span className="text-white font-bold">{step.id}</span>
										</div>
									</div>
								</div>
							))}
						</div>
					</div>

					<div className="text-center mt-12">
						<p className="text-gray-600 mb-6 max-w-3xl mx-auto">
							<em>
								Note: Timelines vary based on project complexity, platform choice, and client responsiveness. We'll
								provide a customized timeline during our initial consultation.
							</em>
						</p>
						<a
							href="#project-questionnaire"
							className="inline-flex items-center px-6 py-3 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700"
						>
							Start Your Project
							<i className="fas fa-arrow-right ml-2"></i>
						</a>
					</div>
				</div>
			</section>

			{/* Project Questionnaire */}
			<section id="project-questionnaire" className="py-20 bg-white">
				<div className="container mx-auto px-4">
					<div className="max-w-4xl mx-auto">
						<div className="text-center mb-12">
							<h2 className="text-3xl md:text-4xl font-bold mb-6">Tell Us About Your Project</h2>
							<p className="text-xl text-gray-600">
								Complete this form to help us understand your requirements and provide an accurate proposal.
							</p>
						</div>

						<div className="bg-gray-50 rounded-xl shadow-lg overflow-hidden">
							<div className="p-8 md:p-12">
								<form id="projectForm" className="space-y-6">
									{/* Project Basics */}
									<fieldset className="border border-gray-200 rounded-lg p-6">
										<legend className="text-lg font-bold px-2">Project Basics</legend>

										<div className="grid grid-cols-1 md:grid-cols-2 gap-6">
											<div>
												<label htmlFor="companyName" className="block text-sm font-medium text-gray-700 mb-1">
													Company Name*
												</label>
												<input
													type="text"
													id="companyName"
													name="companyName"
													required
													className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
												/>
											</div>
											<div>
												<label htmlFor="website" className="block text-sm font-medium text-gray-700 mb-1">
													Current Website (if any)
												</label>
												<input
													type="url"
													id="website"
													name="website"
													className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
												/>
											</div>
										</div>

										<div className="mt-4">
											<label htmlFor="projectDescription" className="block text-sm font-medium text-gray-700 mb-1">
												Project Description*
											</label>
											<textarea
												id="projectDescription"
												name="projectDescription"
												rows="3"
												required
												className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
												placeholder="Briefly describe your eCommerce project, including your products/services, target audience, and business goals."
											></textarea>
										</div>
									</fieldset>

									{/* Platform Preferences */}
									<fieldset className="border border-gray-200 rounded-lg p-6">
										<legend className="text-lg font-bold px-2">Platform Preferences</legend>

										<div className="space-y-4">
											<label className="block text-sm font-medium text-gray-700 mb-2">Preferred Platform*</label>
											<div className="grid grid-cols-1 md:grid-cols-3 gap-4">
												{[
													['shopify', 'Shopify/Shopify Plus'],
													['woocommerce', 'WooCommerce'],
													['magento', 'Magento'],
													['bigcommerce', 'BigCommerce'],
													['custom', 'Custom Solution'],
													['unsure', 'Not Sure (Need Guidance)'],
												].map(([value, label]) => (
													<label key={value} className="flex items-center space-x-3">
														<input
															type="radio"
															name="platform"
															value={value}
															className="h-4 w-4 text-indigo-600 focus:ring-indigo-500"
														/>
														<span className="text-gray-700">{label}</span>
													</label>
												))}
											</div>

											<div className="mt-4">
												<label htmlFor="platformNotes" className="block text-sm font-medium text-gray-700 mb-1">
													Platform Notes
												</label>
												<textarea
													id="platformNotes"
													name="platformNotes"
													rows="2"
													className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
													placeholder="Any specific requirements or preferences regarding the platform?"
												></textarea>
											</div>
										</div>
									</fieldset>

									{/* Project Requirements */}
									<fieldset className="border border-gray-200 rounded-lg p-6">
										<legend className="text-lg font-bold px-2">Project Requirements</legend>

										<div className="space-y-4">
											<div>
												<label className="block text-sm font-medium text-gray-700 mb-2">Required Services*</label>
												<div className="grid grid-cols-1 md:grid-cols-2 gap-4">
													{[
														['design', 'Custom Design & Development'],
														['migration', 'Platform Migration'],
														['integration', 'Third-party Integrations'],
														['seo', 'SEO Optimization'],
														['marketing', 'Digital Marketing'],
														['maintenance', 'Ongoing Maintenance'],
													].map(([value, label]) => (
														<label key={value} className="flex items-start space-x-3">
															<input
																type="checkbox"
																name="services"
																value={value}
																className="h-4 w-4 text-indigo-600 focus:ring-indigo-500 mt-1"
															/>
															<span className="text-gray-700">{label}</span>
														</label>
													))}
												</div>
											</div>

											<div className="grid grid-cols-1 md:grid-cols-2 gap-6">
												<div>
													<label htmlFor="productCount" className="block text-sm font-medium text-gray-700 mb-1">
														Approximate Number of Products*
													</label>
													<select
														id="productCount"
														name="productCount"
														required
														className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
													>
														<option value="">Select an option</option>
														<option value="1-50">1-50</option>
														<option value="51-200">51-200</option>
														<option value="201-1000">201-1,000</option>
														<option value="1001-5000">1,001-5,000</option>
														<option value="5000+">5,000+</option>
													</select>
												</div>
												<div>
													<label htmlFor="launchTimeline" className="block text-sm font-medium text-gray-700 mb-1">
														Desired Launch Timeline*
													</label>
													<select
														id="launchTimeline"
														name="launchTimeline"
														required
														className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
													>
														<option value="">Select an option</option>
														<option value="1-3 months">1-3 months</option>
														<option value="3-6 months">3-6 months</option>
														<option value="6-9 months">6-9 months</option>
														<option value="flexible">Flexible timeline</option>
														<option value="urgent">ASAP (expedited)</option>
													</select>
												</div>
											</div>

											<div>
												<label htmlFor="specificRequirements" className="block text-sm font-medium text-gray-700 mb-1">
													Specific Requirements
												</label>
												<textarea
													id="specificRequirements"
													name="specificRequirements"
													rows="3"
													className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
													placeholder="Any special features, functionalities, or integrations you require?"
												></textarea>
											</div>
										</div>
									</fieldset>

									{/* Budget & Contact Info */}
									<fieldset className="border border-gray-200 rounded-lg p-6">
										<legend className="text-lg font-bold px-2">Budget & Contact Information</legend>

										<div className="grid grid-cols-1 md:grid-cols-2 gap-6">
											<div>
												<label htmlFor="budgetRange" className="block text-sm font-medium text-gray-700 mb-1">
													Estimated Budget Range*
												</label>
												<select
													id="budgetRange"
													name="budgetRange"
													required
													className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
												>
													<option value="">Select an option</option>
													<option value="under-25k">Under $25,000</option>
													<option value="25k-50k">$25,000 - $50,000</option>
													<option value="50k-100k">$50,000 - $100,000</option>
													<option value="100k-250k">$100,000 - $250,000</option>
													<option value="250k-plus">$250,000+</option>
													<option value="unsure">Not sure (need guidance)</option>
												</select>
											</div>
											<div>
												<label htmlFor="referralSource" className="block text-sm font-medium text-gray-700 mb-1">
													How did you hear about us?
												</label>
												<select
													id="referralSource"
													name="referralSource"
													className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
												>
													<option value="">Select an option</option>
													<option value="search">Search Engine (Google, Bing, etc.)</option>
													<option value="social">Social Media</option>
													<option value="referral">Referral</option>
													<option value="event">Industry Event</option>
													<option value="other">Other</option>
												</select>
											</div>
										</div>

										<div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-6">
											<div>
												<label htmlFor="contactName" className="block text-sm font-medium text-gray-700 mb-1">
													Your Name*
												</label>
												<input
													type="text"
													id="contactName"
													name="contactName"
													required
													className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
												/>
											</div>
											<div>
												<label htmlFor="contactEmail" className="block text-sm font-medium text-gray-700 mb-1">
													Email Address*
												</label>
												<input
													type="email"
													id="contactEmail"
													name="contactEmail"
													required
													className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
												/>
											</div>
										</div>

										<div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-6">
											<div>
												<label htmlFor="contactPhone" className="block text-sm font-medium text-gray-700 mb-1">
													Phone Number
												</label>
												<input
													type="tel"
													id="contactPhone"
													name="contactPhone"
													className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
												/>
											</div>
											<div>
												<label htmlFor="contactRole" className="block text-sm font-medium text-gray-700 mb-1">
													Your Role*
												</label>
												<input
													type="text"
													id="contactRole"
													name="contactRole"
													required
													placeholder="e.g., Owner, Marketing Director, etc."
													className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
												/>
											</div>
										</div>
									</fieldset>

									{/* Consent + Submit */}
									<div className="flex items-start">
										<div className="flex items-center h-5">
											<input
												id="agreeTerms"
												name="agreeTerms"
												type="checkbox"
												required
												className="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded"
												defaultChecked
											/>
										</div>
										<div className="ml-3 text-sm">
											<label htmlFor="agreeTerms" className="font-medium text-gray-700">
												I agree to receive communications from EcomReflex about my project inquiry.
											</label>
										</div>
									</div>

									<div className="pt-4">
										<button
											type="submit"
											className="w-full bg-indigo-600 text-white px-6 py-3 rounded-md font-medium hover:bg-indigo-700 transition focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
										>
											Submit Project Details
										</button>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</section>

			{/* What happens after you submit */}
			<section className="py-20 bg-indigo-50">
				<div className="container mx-auto px-4">
					<div className="max-w-4xl mx-auto text-center">
						<h2 className="text-3xl md:text-4xl font-bold mb-6">What Happens After You Submit?</h2>
						<p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
							Here's what you can expect once you've submitted your project details:
						</p>

						<div className="grid grid-cols-1 md:grid-cols-3 gap-8 text-left">
							{/* Step 1 */}
							<div className="bg-white p-6 rounded-lg shadow-md">
								<div className="w-12 h-12 bg-indigo-100 rounded-full flex items-center justify-center mb-4">
									<FaEnvelope className="text-indigo-600 text-xl" />
								</div>
								<h3 className="text-xl font-bold mb-3">Confirmation Email</h3>
								<p className="text-gray-600">
									You'll receive an email confirmation with a copy of your submission and next steps.
								</p>
							</div>

							{/* Step 2 */}
							<div className="bg-white p-6 rounded-lg shadow-md">
								<div className="w-12 h-12 bg-indigo-100 rounded-full flex items-center justify-center mb-4">
									<FaCalendarCheck className="text-indigo-600 text-xl" />
								</div>
								<h3 className="text-xl font-bold mb-3">Scheduling Call</h3>
								<p className="text-gray-600">
									Our team will contact you within 24 hours to schedule your free consultation.
								</p>
							</div>

							{/* Step 3 */}
							<div className="bg-white p-6 rounded-lg shadow-md">
								<div className="w-12 h-12 bg-indigo-100 rounded-full flex items-center justify-center mb-4">
									<FaFileAlt className="text-indigo-600 text-xl" />
								</div>
								<h3 className="text-xl font-bold mb-3">Custom Proposal</h3>
								<p className="text-gray-600">
									Within 3 business days, we'll provide a detailed proposal tailored to your needs.
								</p>
							</div>
						</div>
					</div>
				</div>
			</section>
		</>
	);
}
